apiVersion: route.openshift.io/v1
kind: Route
metadata:
          labels:
            app: todonodejs
            name: frontend
          name: frontend
spec:
  host: todo.apps.ocp5.svtech.gay
  path: "/todo"
  to:
    kind: Service
    name: frontend-apac
    weight: 100
  wildcardPolicy: None
